import type { GetServerSideProps } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { fetchClient } from "@/utils";
import Tiny from "@/components/tiny";

interface NextNextProps {
  name: string;
}

export default function NextNext({ name }: NextNextProps) {
  const [toggle, setToggle] = useState(false);

  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>next dynamic page</h1>
        <h6>(캐시를 하지 않는 ssr 페이지)</h6>
        <main>server side: {name}</main>
        <button type="button" onClick={() => setToggle((prev) => !prev)}>
          show
        </button>
        {toggle && <Tiny />}
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<NextNextProps> = async ({ res }) => {
  const { data } = await fetchClient.get<{ name: string }>("api/random");
  const random = Math.floor(Math.random() * 100);

  return {
    props: {
      name: `dynamic2 king ${data.name} - ${random}`,
    },
  };
};
