import Head from "next/head";
import { ErrorBoundary } from "@/components/common";
import { ErrorChild } from "@/components";

export default function ErrorPage() {
  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ErrorBoundary fallback={<div>something went wrong..</div>}>
          <ErrorChild />
        </ErrorBoundary>
      </main>
    </>
  );
}
