import Head from "next/head";
import Image from "next/image";
import weatherSrc from "../../public/weather.png";

export default function ImagePage() {
  return (
    <>
      <Head>
        <title>nextnext-image</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image src={weatherSrc} alt="날씨" placeholder="blur" priority />
      </main>
    </>
  );
}
