import type { GetServerSideProps } from "next";
import Head from "next/head";
import React, { useRef, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { fetchClient } from "@/utils";
import { Todo } from "global-type";

interface NextNextProps {
  todoList: Array<Todo>;
}

export default function NextNext({ todoList }: NextNextProps) {
  // const { data, isLoading, mutate } = useMutation(() => fetchClient.post());
  const inputRef = useRef<HTMLInputElement>(null);

  const onClick = async () => {
    const id = todoList.length + 1;

    const { data } = await fetchClient.post<Todo, Todo>("/todo", {
      title: inputRef.current?.value as string,
      isCompleted: false,
      id,
    });

    console.log(data);
  };

  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>next next</h1>
        <main>
          <div className="container">
            <div className="input-container">
              <input type="text" ref={inputRef} />
              <button type="button" onClick={onClick}>
                추가
              </button>
            </div>
            {todoList.map((todo) => (
              <div className="todo-item" key={todo.id}>
                {todo.title}
                <input type="checkbox" name={String(todo.id)} checked={todo.isCompleted} />
              </div>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await fetchClient.get<NextNextProps>("/todo");

  return {
    props: {
      todoList: data.todoList,
    },
  };
};
