import type { GetStaticProps } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { fetchClient } from "@/utils";
import Tiny from "@/components/tiny";

interface NextNextProps {
  name: string;
}

export default function NextNext({ name }: NextNextProps) {
  const [toggle, setToggle] = useState(false);
  console.log(`static side${name}`);

  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>next static page</h1>
        <main>static side: {name || 234}</main>
        <button type="button" onClick={() => setToggle((prev) => !prev)}>
          show
        </button>
        {toggle && <Tiny />}
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps<NextNextProps> = async () => {
  const { data } = await fetchClient.get<{ name: string }>("api/random");
  const random = Math.floor(Math.random() * 100);

  return {
    props: {
      name: `static king ${data.name} - ${random}`,
      a: 12,
    },
  };
};
