import type { GetStaticProps } from "next";
import Head from "next/head";
import React, { useState } from "react";
import axios from "axios";
import Tiny from "@/components/tiny";

interface NextNextProps {
  name: string;
}

export default function NextNext({ name }: NextNextProps) {
  const [toggle, setToggle] = useState(false);

  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>next static page</h1>
        <main>static side: {name}</main>
        <button type="button" onClick={() => setToggle((prev) => !prev)}>
          show
        </button>
        {toggle && <Tiny />}
      </div>
    </>
  );
}

export async function fetchApiHello() {
  const url = "http://localhost:3000/api/hello";
  const { data } = await axios.get<{ name: string }>(url);

  return data;
}

export const getStaticProps: GetStaticProps = () => {
  const random = Math.floor(Math.random() * 100);

  return {
    props: {
      name: `king ${random}`,
    },
  };
};
