import type { GetServerSideProps } from "next";
import Head from "next/head";
import React, { useState } from "react";
import axios from "axios";
import Tiny from "@/components/tiny";

interface NextNextProps {
  name: string;
}

export default function NextNext({ name }: NextNextProps) {
  const [toggle, setToggle] = useState(false);

  return (
    <>
      <Head>
        <title>nextnext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>next next</h1>
        <main>server side: {name}</main>
        <button type="button" onClick={() => setToggle((prev) => !prev)}>
          show
        </button>
        {toggle && <Tiny />}
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  // const { todoList } = await getTodo();
  const url = "http://localhost:3000/api/hello";
  const {
    data: { name },
  } = await axios.get<{ name: string }>(url);
  /**
   * @desc next에서 문서 리소스는 no-store로 아예 안함~
   */
  res.setHeader("Cache-Control", "public, max-age=5000");

  return {
    props: {
      name,
    },
  };
};
